name: test_bazel

on: [push, pull_request]

jobs:
  bazel:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: bazel-contrib/setup-bazel@0.13.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true
    - name: Test Main
      run : 'bazel test //...'
    - name: Test Example
      working-directory: examples/bazel
      run : 'bazel test //...'
